// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace edgesched {

static const char* Inference_method_names[] = {
  "/edgesched.Inference/Predict",
  "/edgesched.Inference/HealthCheck",
};

std::unique_ptr< Inference::Stub> Inference::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Inference::Stub> stub(new Inference::Stub(channel, options));
  return stub;
}

Inference::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(Inference_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(Inference_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Inference::Stub::Predict(::grpc::ClientContext* context, const ::edgesched::PredictRequest& request, ::edgesched::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::edgesched::PredictRequest, ::edgesched::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void Inference::Stub::async::Predict(::grpc::ClientContext* context, const ::edgesched::PredictRequest* request, ::edgesched::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::edgesched::PredictRequest, ::edgesched::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void Inference::Stub::async::Predict(::grpc::ClientContext* context, const ::edgesched::PredictRequest* request, ::edgesched::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::edgesched::PredictResponse>* Inference::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::edgesched::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::edgesched::PredictResponse, ::edgesched::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::edgesched::PredictResponse>* Inference::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::edgesched::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Inference::Stub::HealthCheck(::grpc::ClientContext* context, const ::edgesched::HealthCheckRequest& request, ::edgesched::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::edgesched::HealthCheckRequest, ::edgesched::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void Inference::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::edgesched::HealthCheckRequest* request, ::edgesched::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::edgesched::HealthCheckRequest, ::edgesched::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void Inference::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::edgesched::HealthCheckRequest* request, ::edgesched::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::edgesched::HealthCheckResponse>* Inference::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::edgesched::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::edgesched::HealthCheckResponse, ::edgesched::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::edgesched::HealthCheckResponse>* Inference::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::edgesched::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

Inference::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Inference_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Inference::Service, ::edgesched::PredictRequest, ::edgesched::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Inference::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edgesched::PredictRequest* req,
             ::edgesched::PredictResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Inference_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Inference::Service, ::edgesched::HealthCheckRequest, ::edgesched::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Inference::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edgesched::HealthCheckRequest* req,
             ::edgesched::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

Inference::Service::~Service() {
}

::grpc::Status Inference::Service::Predict(::grpc::ServerContext* context, const ::edgesched::PredictRequest* request, ::edgesched::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Inference::Service::HealthCheck(::grpc::ServerContext* context, const ::edgesched::HealthCheckRequest* request, ::edgesched::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace edgesched

