// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_inference_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_inference_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_inference_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_inference_2eproto;
namespace edgesched {
class Detection;
struct DetectionDefaultTypeInternal;
extern DetectionDefaultTypeInternal _Detection_default_instance_;
class HealthCheckRequest;
struct HealthCheckRequestDefaultTypeInternal;
extern HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;
class HealthCheckResponse;
struct HealthCheckResponseDefaultTypeInternal;
extern HealthCheckResponseDefaultTypeInternal _HealthCheckResponse_default_instance_;
class PredictRequest;
struct PredictRequestDefaultTypeInternal;
extern PredictRequestDefaultTypeInternal _PredictRequest_default_instance_;
class PredictResponse;
struct PredictResponseDefaultTypeInternal;
extern PredictResponseDefaultTypeInternal _PredictResponse_default_instance_;
}  // namespace edgesched
PROTOBUF_NAMESPACE_OPEN
template<> ::edgesched::Detection* Arena::CreateMaybeMessage<::edgesched::Detection>(Arena*);
template<> ::edgesched::HealthCheckRequest* Arena::CreateMaybeMessage<::edgesched::HealthCheckRequest>(Arena*);
template<> ::edgesched::HealthCheckResponse* Arena::CreateMaybeMessage<::edgesched::HealthCheckResponse>(Arena*);
template<> ::edgesched::PredictRequest* Arena::CreateMaybeMessage<::edgesched::PredictRequest>(Arena*);
template<> ::edgesched::PredictResponse* Arena::CreateMaybeMessage<::edgesched::PredictResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace edgesched {

// ===================================================================

class PredictRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:edgesched.PredictRequest) */ {
 public:
  inline PredictRequest() : PredictRequest(nullptr) {}
  ~PredictRequest() override;
  explicit PROTOBUF_CONSTEXPR PredictRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PredictRequest(const PredictRequest& from);
  PredictRequest(PredictRequest&& from) noexcept
    : PredictRequest() {
    *this = ::std::move(from);
  }

  inline PredictRequest& operator=(const PredictRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictRequest& operator=(PredictRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PredictRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PredictRequest* internal_default_instance() {
    return reinterpret_cast<const PredictRequest*>(
               &_PredictRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PredictRequest& a, PredictRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PredictRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PredictRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PredictRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PredictRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PredictRequest& from) {
    PredictRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PredictRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "edgesched.PredictRequest";
  }
  protected:
  explicit PredictRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 1,
  };
  // bytes image_data = 1;
  void clear_image_data();
  const std::string& image_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_data();
  PROTOBUF_NODISCARD std::string* release_image_data();
  void set_allocated_image_data(std::string* image_data);
  private:
  const std::string& _internal_image_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(const std::string& value);
  std::string* _internal_mutable_image_data();
  public:

  // @@protoc_insertion_point(class_scope:edgesched.PredictRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class Detection final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:edgesched.Detection) */ {
 public:
  inline Detection() : Detection(nullptr) {}
  ~Detection() override;
  explicit PROTOBUF_CONSTEXPR Detection(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Detection(const Detection& from);
  Detection(Detection&& from) noexcept
    : Detection() {
    *this = ::std::move(from);
  }

  inline Detection& operator=(const Detection& from) {
    CopyFrom(from);
    return *this;
  }
  inline Detection& operator=(Detection&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Detection& default_instance() {
    return *internal_default_instance();
  }
  static inline const Detection* internal_default_instance() {
    return reinterpret_cast<const Detection*>(
               &_Detection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Detection& a, Detection& b) {
    a.Swap(&b);
  }
  inline void Swap(Detection* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Detection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Detection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Detection>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Detection& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Detection& from) {
    Detection::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Detection* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "edgesched.Detection";
  }
  protected:
  explicit Detection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClassNameFieldNumber = 7,
    kX1FieldNumber = 1,
    kY1FieldNumber = 2,
    kX2FieldNumber = 3,
    kY2FieldNumber = 4,
    kConfidenceFieldNumber = 5,
    kClassIdFieldNumber = 6,
  };
  // string class_name = 7;
  void clear_class_name();
  const std::string& class_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_class_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_class_name();
  PROTOBUF_NODISCARD std::string* release_class_name();
  void set_allocated_class_name(std::string* class_name);
  private:
  const std::string& _internal_class_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_class_name(const std::string& value);
  std::string* _internal_mutable_class_name();
  public:

  // float x1 = 1;
  void clear_x1();
  float x1() const;
  void set_x1(float value);
  private:
  float _internal_x1() const;
  void _internal_set_x1(float value);
  public:

  // float y1 = 2;
  void clear_y1();
  float y1() const;
  void set_y1(float value);
  private:
  float _internal_y1() const;
  void _internal_set_y1(float value);
  public:

  // float x2 = 3;
  void clear_x2();
  float x2() const;
  void set_x2(float value);
  private:
  float _internal_x2() const;
  void _internal_set_x2(float value);
  public:

  // float y2 = 4;
  void clear_y2();
  float y2() const;
  void set_y2(float value);
  private:
  float _internal_y2() const;
  void _internal_set_y2(float value);
  public:

  // float confidence = 5;
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // int32 class_id = 6;
  void clear_class_id();
  int32_t class_id() const;
  void set_class_id(int32_t value);
  private:
  int32_t _internal_class_id() const;
  void _internal_set_class_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:edgesched.Detection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_name_;
    float x1_;
    float y1_;
    float x2_;
    float y2_;
    float confidence_;
    int32_t class_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class PredictResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:edgesched.PredictResponse) */ {
 public:
  inline PredictResponse() : PredictResponse(nullptr) {}
  ~PredictResponse() override;
  explicit PROTOBUF_CONSTEXPR PredictResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PredictResponse(const PredictResponse& from);
  PredictResponse(PredictResponse&& from) noexcept
    : PredictResponse() {
    *this = ::std::move(from);
  }

  inline PredictResponse& operator=(const PredictResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PredictResponse& operator=(PredictResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PredictResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PredictResponse* internal_default_instance() {
    return reinterpret_cast<const PredictResponse*>(
               &_PredictResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PredictResponse& a, PredictResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PredictResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PredictResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PredictResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PredictResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PredictResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PredictResponse& from) {
    PredictResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PredictResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "edgesched.PredictResponse";
  }
  protected:
  explicit PredictResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetectionsFieldNumber = 1,
    kPreprocessMsFieldNumber = 2,
    kInferenceMsFieldNumber = 3,
    kPostprocessMsFieldNumber = 4,
  };
  // repeated .edgesched.Detection detections = 1;
  int detections_size() const;
  private:
  int _internal_detections_size() const;
  public:
  void clear_detections();
  ::edgesched::Detection* mutable_detections(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::edgesched::Detection >*
      mutable_detections();
  private:
  const ::edgesched::Detection& _internal_detections(int index) const;
  ::edgesched::Detection* _internal_add_detections();
  public:
  const ::edgesched::Detection& detections(int index) const;
  ::edgesched::Detection* add_detections();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::edgesched::Detection >&
      detections() const;

  // float preprocess_ms = 2;
  void clear_preprocess_ms();
  float preprocess_ms() const;
  void set_preprocess_ms(float value);
  private:
  float _internal_preprocess_ms() const;
  void _internal_set_preprocess_ms(float value);
  public:

  // float inference_ms = 3;
  void clear_inference_ms();
  float inference_ms() const;
  void set_inference_ms(float value);
  private:
  float _internal_inference_ms() const;
  void _internal_set_inference_ms(float value);
  public:

  // float postprocess_ms = 4;
  void clear_postprocess_ms();
  float postprocess_ms() const;
  void set_postprocess_ms(float value);
  private:
  float _internal_postprocess_ms() const;
  void _internal_set_postprocess_ms(float value);
  public:

  // @@protoc_insertion_point(class_scope:edgesched.PredictResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::edgesched::Detection > detections_;
    float preprocess_ms_;
    float inference_ms_;
    float postprocess_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:edgesched.HealthCheckRequest) */ {
 public:
  inline HealthCheckRequest() : HealthCheckRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckRequest(const HealthCheckRequest& from);
  HealthCheckRequest(HealthCheckRequest&& from) noexcept
    : HealthCheckRequest() {
    *this = ::std::move(from);
  }

  inline HealthCheckRequest& operator=(const HealthCheckRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckRequest& operator=(HealthCheckRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckRequest* internal_default_instance() {
    return reinterpret_cast<const HealthCheckRequest*>(
               &_HealthCheckRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HealthCheckRequest& a, HealthCheckRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HealthCheckRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HealthCheckRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "edgesched.HealthCheckRequest";
  }
  protected:
  explicit HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:edgesched.HealthCheckRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:edgesched.HealthCheckResponse) */ {
 public:
  inline HealthCheckResponse() : HealthCheckResponse(nullptr) {}
  ~HealthCheckResponse() override;
  explicit PROTOBUF_CONSTEXPR HealthCheckResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckResponse(const HealthCheckResponse& from);
  HealthCheckResponse(HealthCheckResponse&& from) noexcept
    : HealthCheckResponse() {
    *this = ::std::move(from);
  }

  inline HealthCheckResponse& operator=(const HealthCheckResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckResponse& operator=(HealthCheckResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckResponse* internal_default_instance() {
    return reinterpret_cast<const HealthCheckResponse*>(
               &_HealthCheckResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(HealthCheckResponse& a, HealthCheckResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HealthCheckResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HealthCheckResponse& from) {
    HealthCheckResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthCheckResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "edgesched.HealthCheckResponse";
  }
  protected:
  explicit HealthCheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEngineNameFieldNumber = 2,
    kServingFieldNumber = 1,
  };
  // string engine_name = 2;
  void clear_engine_name();
  const std::string& engine_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_engine_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_engine_name();
  PROTOBUF_NODISCARD std::string* release_engine_name();
  void set_allocated_engine_name(std::string* engine_name);
  private:
  const std::string& _internal_engine_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_engine_name(const std::string& value);
  std::string* _internal_mutable_engine_name();
  public:

  // bool serving = 1;
  void clear_serving();
  bool serving() const;
  void set_serving(bool value);
  private:
  bool _internal_serving() const;
  void _internal_set_serving(bool value);
  public:

  // @@protoc_insertion_point(class_scope:edgesched.HealthCheckResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr engine_name_;
    bool serving_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PredictRequest

// bytes image_data = 1;
inline void PredictRequest::clear_image_data() {
  _impl_.image_data_.ClearToEmpty();
}
inline const std::string& PredictRequest::image_data() const {
  // @@protoc_insertion_point(field_get:edgesched.PredictRequest.image_data)
  return _internal_image_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PredictRequest::set_image_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:edgesched.PredictRequest.image_data)
}
inline std::string* PredictRequest::mutable_image_data() {
  std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:edgesched.PredictRequest.image_data)
  return _s;
}
inline const std::string& PredictRequest::_internal_image_data() const {
  return _impl_.image_data_.Get();
}
inline void PredictRequest::_internal_set_image_data(const std::string& value) {
  
  _impl_.image_data_.Set(value, GetArenaForAllocation());
}
inline std::string* PredictRequest::_internal_mutable_image_data() {
  
  return _impl_.image_data_.Mutable(GetArenaForAllocation());
}
inline std::string* PredictRequest::release_image_data() {
  // @@protoc_insertion_point(field_release:edgesched.PredictRequest.image_data)
  return _impl_.image_data_.Release();
}
inline void PredictRequest::set_allocated_image_data(std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  _impl_.image_data_.SetAllocated(image_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:edgesched.PredictRequest.image_data)
}

// -------------------------------------------------------------------

// Detection

// float x1 = 1;
inline void Detection::clear_x1() {
  _impl_.x1_ = 0;
}
inline float Detection::_internal_x1() const {
  return _impl_.x1_;
}
inline float Detection::x1() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.x1)
  return _internal_x1();
}
inline void Detection::_internal_set_x1(float value) {
  
  _impl_.x1_ = value;
}
inline void Detection::set_x1(float value) {
  _internal_set_x1(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.x1)
}

// float y1 = 2;
inline void Detection::clear_y1() {
  _impl_.y1_ = 0;
}
inline float Detection::_internal_y1() const {
  return _impl_.y1_;
}
inline float Detection::y1() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.y1)
  return _internal_y1();
}
inline void Detection::_internal_set_y1(float value) {
  
  _impl_.y1_ = value;
}
inline void Detection::set_y1(float value) {
  _internal_set_y1(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.y1)
}

// float x2 = 3;
inline void Detection::clear_x2() {
  _impl_.x2_ = 0;
}
inline float Detection::_internal_x2() const {
  return _impl_.x2_;
}
inline float Detection::x2() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.x2)
  return _internal_x2();
}
inline void Detection::_internal_set_x2(float value) {
  
  _impl_.x2_ = value;
}
inline void Detection::set_x2(float value) {
  _internal_set_x2(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.x2)
}

// float y2 = 4;
inline void Detection::clear_y2() {
  _impl_.y2_ = 0;
}
inline float Detection::_internal_y2() const {
  return _impl_.y2_;
}
inline float Detection::y2() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.y2)
  return _internal_y2();
}
inline void Detection::_internal_set_y2(float value) {
  
  _impl_.y2_ = value;
}
inline void Detection::set_y2(float value) {
  _internal_set_y2(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.y2)
}

// float confidence = 5;
inline void Detection::clear_confidence() {
  _impl_.confidence_ = 0;
}
inline float Detection::_internal_confidence() const {
  return _impl_.confidence_;
}
inline float Detection::confidence() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.confidence)
  return _internal_confidence();
}
inline void Detection::_internal_set_confidence(float value) {
  
  _impl_.confidence_ = value;
}
inline void Detection::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.confidence)
}

// int32 class_id = 6;
inline void Detection::clear_class_id() {
  _impl_.class_id_ = 0;
}
inline int32_t Detection::_internal_class_id() const {
  return _impl_.class_id_;
}
inline int32_t Detection::class_id() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.class_id)
  return _internal_class_id();
}
inline void Detection::_internal_set_class_id(int32_t value) {
  
  _impl_.class_id_ = value;
}
inline void Detection::set_class_id(int32_t value) {
  _internal_set_class_id(value);
  // @@protoc_insertion_point(field_set:edgesched.Detection.class_id)
}

// string class_name = 7;
inline void Detection::clear_class_name() {
  _impl_.class_name_.ClearToEmpty();
}
inline const std::string& Detection::class_name() const {
  // @@protoc_insertion_point(field_get:edgesched.Detection.class_name)
  return _internal_class_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Detection::set_class_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.class_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:edgesched.Detection.class_name)
}
inline std::string* Detection::mutable_class_name() {
  std::string* _s = _internal_mutable_class_name();
  // @@protoc_insertion_point(field_mutable:edgesched.Detection.class_name)
  return _s;
}
inline const std::string& Detection::_internal_class_name() const {
  return _impl_.class_name_.Get();
}
inline void Detection::_internal_set_class_name(const std::string& value) {
  
  _impl_.class_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Detection::_internal_mutable_class_name() {
  
  return _impl_.class_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Detection::release_class_name() {
  // @@protoc_insertion_point(field_release:edgesched.Detection.class_name)
  return _impl_.class_name_.Release();
}
inline void Detection::set_allocated_class_name(std::string* class_name) {
  if (class_name != nullptr) {
    
  } else {
    
  }
  _impl_.class_name_.SetAllocated(class_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.class_name_.IsDefault()) {
    _impl_.class_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:edgesched.Detection.class_name)
}

// -------------------------------------------------------------------

// PredictResponse

// repeated .edgesched.Detection detections = 1;
inline int PredictResponse::_internal_detections_size() const {
  return _impl_.detections_.size();
}
inline int PredictResponse::detections_size() const {
  return _internal_detections_size();
}
inline void PredictResponse::clear_detections() {
  _impl_.detections_.Clear();
}
inline ::edgesched::Detection* PredictResponse::mutable_detections(int index) {
  // @@protoc_insertion_point(field_mutable:edgesched.PredictResponse.detections)
  return _impl_.detections_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::edgesched::Detection >*
PredictResponse::mutable_detections() {
  // @@protoc_insertion_point(field_mutable_list:edgesched.PredictResponse.detections)
  return &_impl_.detections_;
}
inline const ::edgesched::Detection& PredictResponse::_internal_detections(int index) const {
  return _impl_.detections_.Get(index);
}
inline const ::edgesched::Detection& PredictResponse::detections(int index) const {
  // @@protoc_insertion_point(field_get:edgesched.PredictResponse.detections)
  return _internal_detections(index);
}
inline ::edgesched::Detection* PredictResponse::_internal_add_detections() {
  return _impl_.detections_.Add();
}
inline ::edgesched::Detection* PredictResponse::add_detections() {
  ::edgesched::Detection* _add = _internal_add_detections();
  // @@protoc_insertion_point(field_add:edgesched.PredictResponse.detections)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::edgesched::Detection >&
PredictResponse::detections() const {
  // @@protoc_insertion_point(field_list:edgesched.PredictResponse.detections)
  return _impl_.detections_;
}

// float preprocess_ms = 2;
inline void PredictResponse::clear_preprocess_ms() {
  _impl_.preprocess_ms_ = 0;
}
inline float PredictResponse::_internal_preprocess_ms() const {
  return _impl_.preprocess_ms_;
}
inline float PredictResponse::preprocess_ms() const {
  // @@protoc_insertion_point(field_get:edgesched.PredictResponse.preprocess_ms)
  return _internal_preprocess_ms();
}
inline void PredictResponse::_internal_set_preprocess_ms(float value) {
  
  _impl_.preprocess_ms_ = value;
}
inline void PredictResponse::set_preprocess_ms(float value) {
  _internal_set_preprocess_ms(value);
  // @@protoc_insertion_point(field_set:edgesched.PredictResponse.preprocess_ms)
}

// float inference_ms = 3;
inline void PredictResponse::clear_inference_ms() {
  _impl_.inference_ms_ = 0;
}
inline float PredictResponse::_internal_inference_ms() const {
  return _impl_.inference_ms_;
}
inline float PredictResponse::inference_ms() const {
  // @@protoc_insertion_point(field_get:edgesched.PredictResponse.inference_ms)
  return _internal_inference_ms();
}
inline void PredictResponse::_internal_set_inference_ms(float value) {
  
  _impl_.inference_ms_ = value;
}
inline void PredictResponse::set_inference_ms(float value) {
  _internal_set_inference_ms(value);
  // @@protoc_insertion_point(field_set:edgesched.PredictResponse.inference_ms)
}

// float postprocess_ms = 4;
inline void PredictResponse::clear_postprocess_ms() {
  _impl_.postprocess_ms_ = 0;
}
inline float PredictResponse::_internal_postprocess_ms() const {
  return _impl_.postprocess_ms_;
}
inline float PredictResponse::postprocess_ms() const {
  // @@protoc_insertion_point(field_get:edgesched.PredictResponse.postprocess_ms)
  return _internal_postprocess_ms();
}
inline void PredictResponse::_internal_set_postprocess_ms(float value) {
  
  _impl_.postprocess_ms_ = value;
}
inline void PredictResponse::set_postprocess_ms(float value) {
  _internal_set_postprocess_ms(value);
  // @@protoc_insertion_point(field_set:edgesched.PredictResponse.postprocess_ms)
}

// -------------------------------------------------------------------

// HealthCheckRequest

// -------------------------------------------------------------------

// HealthCheckResponse

// bool serving = 1;
inline void HealthCheckResponse::clear_serving() {
  _impl_.serving_ = false;
}
inline bool HealthCheckResponse::_internal_serving() const {
  return _impl_.serving_;
}
inline bool HealthCheckResponse::serving() const {
  // @@protoc_insertion_point(field_get:edgesched.HealthCheckResponse.serving)
  return _internal_serving();
}
inline void HealthCheckResponse::_internal_set_serving(bool value) {
  
  _impl_.serving_ = value;
}
inline void HealthCheckResponse::set_serving(bool value) {
  _internal_set_serving(value);
  // @@protoc_insertion_point(field_set:edgesched.HealthCheckResponse.serving)
}

// string engine_name = 2;
inline void HealthCheckResponse::clear_engine_name() {
  _impl_.engine_name_.ClearToEmpty();
}
inline const std::string& HealthCheckResponse::engine_name() const {
  // @@protoc_insertion_point(field_get:edgesched.HealthCheckResponse.engine_name)
  return _internal_engine_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HealthCheckResponse::set_engine_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.engine_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:edgesched.HealthCheckResponse.engine_name)
}
inline std::string* HealthCheckResponse::mutable_engine_name() {
  std::string* _s = _internal_mutable_engine_name();
  // @@protoc_insertion_point(field_mutable:edgesched.HealthCheckResponse.engine_name)
  return _s;
}
inline const std::string& HealthCheckResponse::_internal_engine_name() const {
  return _impl_.engine_name_.Get();
}
inline void HealthCheckResponse::_internal_set_engine_name(const std::string& value) {
  
  _impl_.engine_name_.Set(value, GetArenaForAllocation());
}
inline std::string* HealthCheckResponse::_internal_mutable_engine_name() {
  
  return _impl_.engine_name_.Mutable(GetArenaForAllocation());
}
inline std::string* HealthCheckResponse::release_engine_name() {
  // @@protoc_insertion_point(field_release:edgesched.HealthCheckResponse.engine_name)
  return _impl_.engine_name_.Release();
}
inline void HealthCheckResponse::set_allocated_engine_name(std::string* engine_name) {
  if (engine_name != nullptr) {
    
  } else {
    
  }
  _impl_.engine_name_.SetAllocated(engine_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.engine_name_.IsDefault()) {
    _impl_.engine_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:edgesched.HealthCheckResponse.engine_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace edgesched

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
